name: Meita Collection

description: Koleksi Fashion Berkualitas

avatar: /images/logo/MC.webp


footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


disqus:
google_analytics:
reCAPTCHA-key: 6LdPL-wZAAAAAAzUvjEWXHGLAgKL78wBzB1IR8t7

url: https://meita-collection.netlify.app

baseurl: ""

permalink: /:title


collections:
  products:
    output: true


defaults:
- scope:
    type: blogs
  values:
    layout: post
- scope:
    type: pages
  values:
    layout: page
- scope:
    type: products
  values:
    layout: product

version: v1.2.0

kramdown:

  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

jekyll-archives:
  enabled:
    - categories
    - tags

  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
